name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: (linux) install vulkan sdk
      run: |
        sudo apt update -y
        sudo apt install -y mesa-vulkan-drivers
    - uses: actions-rs/toolchain@v1
      with:
       toolchain: stable
       target: x86_64-unknown-linux-gnu
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build
    - name: Run doc tests
      run: cargo test --doc -- --nocapture
    - name: Run lib tests
      run: cargo test --lib -- --nocapture
    - name: Linting
      run: cargo clippy -- -D warnings -D clippy::pedantic -D clippy::nursery
  build-wasm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions-rs/toolchain@v1
      with:
       toolchain: stable
       target: wasm32-unknown-unknown
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --target=wasm32-unknown-unknown
    # no tests becuase you can't run .wasm files
    # - name: Run tests
    #   run: cargo test --target=wasm32-unknown-unknown --features webgl
    - name: Linting
      run: cargo clippy --target=wasm32-unknown-unknown -- -D warnings -D clippy::pedantic -D clippy::nursery
  build-wasm-webgl:
    runs-on: ubuntu-latest
    steps:
    - uses: actions-rs/toolchain@v1
      with:
       toolchain: stable
       target: wasm32-unknown-unknown
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --target=wasm32-unknown-unknown --features webgl
    # no tests becuase you can't run .wasm files
    # - name: Run tests
    #   run: cargo test --target=wasm32-unknown-unknown --features webgl
    - name: Linting
      run: cargo clippy --target=wasm32-unknown-unknown --features webgl -- -D warnings -D clippy::pedantic -D clippy::nursery
